
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author visa
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginWithIPPort
     */
    public LoginGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        ipPortPanel = new javax.swing.JPanel();
        ipLabel = new javax.swing.JLabel();
        ipTextField = new javax.swing.JTextField();
        ipLine = new java.awt.Panel();
        portLabel = new javax.swing.JLabel();
        portLine = new java.awt.Panel();
        portTextField = new javax.swing.JTextField();
        usernamePasswordPanel = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameLine = new java.awt.Panel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordLine = new java.awt.Panel();
        buttonPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        signupPrompt = new javax.swing.JLabel();
        signupButton = new javax.swing.JButton();
        editAccountButton = new javax.swing.JButton();
        deleteAccountButton = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        loginTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginPanel.setBackground(new java.awt.Color(242, 243, 244));
        loginPanel.setFont(new java.awt.Font("Avenir Next", Font.PLAIN, 13)); // NOI18N
        loginPanel.setPreferredSize(new java.awt.Dimension(350, 670));

        ipPortPanel.setBackground(new java.awt.Color(242, 243, 244));

        ipLabel.setBackground(new java.awt.Color(204, 204, 204));
        ipLabel.setFont(new java.awt.Font("Avenir Next", Font.PLAIN, 18)); // NOI18N
        ipLabel.setForeground(new java.awt.Color(99, 110, 114));
        ipLabel.setText("Server IP");
        ipLabel.setToolTipText("Server IP");

        ipTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        ipTextField.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        ipTextField.setForeground(new java.awt.Color(121, 125, 127));
        ipTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ipTextField.setToolTipText("Enter the server IP");
        ipTextField.setActionCommand("<Not Set>");
        ipTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ipTextField.setPreferredSize(new java.awt.Dimension(11, 30));

        ipLine.setBackground(new java.awt.Color(99, 110, 114));
        ipLine.setPreferredSize(new java.awt.Dimension(200, 1));

        javax.swing.GroupLayout ipLineLayout = new javax.swing.GroupLayout(ipLine);
        ipLine.setLayout(ipLineLayout);
        ipLineLayout.setHorizontalGroup(
                ipLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        ipLineLayout.setVerticalGroup(
                ipLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1, Short.MAX_VALUE)
        );

        portLabel.setBackground(new java.awt.Color(204, 204, 204));
        portLabel.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        portLabel.setForeground(new java.awt.Color(99, 110, 114));
        portLabel.setText("Server Port");
        portLabel.setToolTipText("Server Port");

        portLine.setBackground(new java.awt.Color(99, 110, 114));
        portLine.setPreferredSize(new java.awt.Dimension(200, 1));

        javax.swing.GroupLayout portLineLayout = new javax.swing.GroupLayout(portLine);
        portLine.setLayout(portLineLayout);
        portLineLayout.setHorizontalGroup(
                portLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        portLineLayout.setVerticalGroup(
                portLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1, Short.MAX_VALUE)
        );

        portTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        portTextField.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        portTextField.setForeground(new java.awt.Color(121, 125, 127));
        portTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        portTextField.setToolTipText("Enter the server port");
        portTextField.setActionCommand("<Not Set>");
        portTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        portTextField.setPreferredSize(new java.awt.Dimension(11, 30));

        javax.swing.GroupLayout ipPortPanelLayout = new javax.swing.GroupLayout(ipPortPanel);
        ipPortPanel.setLayout(ipPortPanelLayout);
        ipPortPanelLayout.setHorizontalGroup(
                ipPortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ipPortPanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(ipPortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ipLine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ipTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(portLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(portLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(portTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(72, 72, 72))
        );
        ipPortPanelLayout.setVerticalGroup(
                ipPortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ipPortPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ipLabel)
                                .addGap(0, 0, 0)
                                .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ipLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(portLabel)
                                .addGap(3, 3, 3)
                                .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(portLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
        );

        usernamePasswordPanel.setBackground(new java.awt.Color(242, 243, 244));

        usernameTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        usernameTextField.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(121, 125, 127));
        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameTextField.setToolTipText("Enter username");
        usernameTextField.setActionCommand("<Not Set>");
        usernameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usernameTextField.setPreferredSize(new java.awt.Dimension(11, 30));

        usernameLabel.setBackground(new java.awt.Color(204, 204, 204));
        usernameLabel.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(99, 110, 114));
        usernameLabel.setText("Username");
        usernameLabel.setToolTipText("Username");

        usernameLine.setBackground(new java.awt.Color(99, 110, 114));
        usernameLine.setPreferredSize(new java.awt.Dimension(200, 1));

        javax.swing.GroupLayout usernameLineLayout = new javax.swing.GroupLayout(usernameLine);
        usernameLine.setLayout(usernameLineLayout);
        usernameLineLayout.setHorizontalGroup(
                usernameLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        usernameLineLayout.setVerticalGroup(
                usernameLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1, Short.MAX_VALUE)
        );

        passwordLabel.setBackground(new java.awt.Color(204, 204, 204));
        passwordLabel.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(99, 110, 114));
        passwordLabel.setText("Password");
        passwordLabel.setToolTipText("Password");

        passwordField.setBackground(new java.awt.Color(255, 255, 255, 0));
        passwordField.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        passwordField.setForeground(new java.awt.Color(121, 125, 127));
        passwordField.setToolTipText("Enter password");
        passwordField.setActionCommand("<Not Set>");
        passwordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        passwordField.setPreferredSize(new java.awt.Dimension(11, 30));

        passwordLine.setBackground(new java.awt.Color(99, 110, 114));
        passwordLine.setPreferredSize(new java.awt.Dimension(200, 1));

        javax.swing.GroupLayout passwordLineLayout = new javax.swing.GroupLayout(passwordLine);
        passwordLine.setLayout(passwordLineLayout);
        passwordLineLayout.setHorizontalGroup(
                passwordLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        passwordLineLayout.setVerticalGroup(
                passwordLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout usernamePasswordPanelLayout = new javax.swing.GroupLayout(usernamePasswordPanel);
        usernamePasswordPanel.setLayout(usernamePasswordPanelLayout);
        usernamePasswordPanelLayout.setHorizontalGroup(
                usernamePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usernamePasswordPanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(usernamePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(usernameLine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(usernameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(passwordLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(72, 72, 72))
        );
        usernamePasswordPanelLayout.setVerticalGroup(
                usernamePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usernamePasswordPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usernameLabel)
                                .addGap(0, 0, 0)
                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(usernameLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(passwordLabel)
                                .addGap(4, 4, 4)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(passwordLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
        );

        buttonPanel.setBackground(new java.awt.Color(242, 243, 244));

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(99, 110, 114));
        loginButton.setText("Log In");
        loginButton.setToolTipText("Log In");
        loginButton.setActionCommand("");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        signupPrompt.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        signupPrompt.setForeground(new java.awt.Color(153, 153, 153));
        signupPrompt.setText("Don't have an account?");
        signupPrompt.setToolTipText("Don't have an account?");

        signupButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        signupButton.setForeground(new java.awt.Color(153, 153, 153));
        signupButton.setText("Sign Up");
        signupButton.setToolTipText("Sign Up");
        signupButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        signupButton.setBorderPainted(false);
        signupButton.setContentAreaFilled(false);
        signupButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        editAccountButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        editAccountButton.setForeground(new java.awt.Color(153, 153, 153));
        editAccountButton.setText("Edit Account");
        editAccountButton.setToolTipText("Edit Account");
        editAccountButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        editAccountButton.setBorderPainted(false);
        editAccountButton.setContentAreaFilled(false);

        deleteAccountButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        deleteAccountButton.setForeground(new java.awt.Color(153, 153, 153));
        deleteAccountButton.setText("Delete Account");
        deleteAccountButton.setToolTipText("Delete Account");
        deleteAccountButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        deleteAccountButton.setBorderPainted(false);
        deleteAccountButton.setContentAreaFilled(false);


        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
                buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(buttonPanelLayout.createSequentialGroup()
                                .addContainerGap(78, Short.MAX_VALUE)
                                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(buttonPanelLayout.createSequentialGroup()
                                                .addComponent(editAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(deleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(buttonPanelLayout.createSequentialGroup()
                                                .addComponent(signupPrompt)
                                                .addGap(0, 0, 0)
                                                .addComponent(signupButton)))
                                .addContainerGap(81, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
                buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(buttonPanelLayout.createSequentialGroup()
                                .addComponent(loginButton)
                                .addGap(28, 28, 28)
                                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(signupPrompt)
                                        .addComponent(signupButton))
                                .addGap(18, 18, 18)
                                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(editAccountButton)
                                        .addComponent(deleteAccountButton))
                                .addContainerGap(47, Short.MAX_VALUE))
        );

        titlePanel.setBackground(new java.awt.Color(242, 243, 244));

        loginTitle.setBackground(new java.awt.Color(242, 243, 244));
        loginTitle.setFont(new java.awt.Font("Avenir Next", 0, 50)); // NOI18N
        loginTitle.setForeground(new java.awt.Color(45, 52, 54));
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("Login");
        loginTitle.setToolTipText("Login");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
                titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
                titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
                loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ipPortPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usernamePasswordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginPanelLayout.setVerticalGroup(
                loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipPortPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(usernamePasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JButton editAccountButton;
    private javax.swing.JLabel ipLabel;
    private java.awt.Panel ipLine;
    private javax.swing.JPanel ipPortPanel;
    private javax.swing.JTextField ipTextField;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private java.awt.Panel passwordLine;
    private javax.swing.JLabel portLabel;
    private java.awt.Panel portLine;
    private javax.swing.JTextField portTextField;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel signupPrompt;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel usernameLabel;
    private java.awt.Panel usernameLine;
    private javax.swing.JPanel usernamePasswordPanel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration

    /**
     * Getter and Setter Methods
     */
    //getters and setters for Login Button
    public JButton getLoginButton() {
        return loginButton;
    }
    public void setLoginButton(JButton loginButton) {
        this.loginButton = loginButton;
    }

    //getters and setters for IP Text Field
    public JTextField getipTextField() {
        return ipTextField;
    }
    public void setipTextField(JTextField ipTextField) {
        this.ipTextField = ipTextField;
    }

    //getters and setters for Password Field
    public JPasswordField getPasswordField() {
        return passwordField;
    }
    public void setPasswordField(JPasswordField passwordField) {
        this.passwordField = passwordField;
    }

    //getters and setters for Port Text Field
    public JTextField getPortTextField() {
        return portTextField;
    }
    public void setPortTextField(JTextField portTextField) {
        this.portTextField = portTextField;
    }

    //getters and setters for Sign Up Button
    public JButton getSignupButton() {
        return signupButton;
    }
    public void setSignupButton(JButton signupButton) {
        this.signupButton = signupButton;
    }

    //getters and setters for Username Text Field
    public JTextField getUsernameTextField() {
        return usernameTextField;
    }
    public void setUsernameTextField(JTextField usernameTextField) {
        this.usernameTextField = usernameTextField;
    }

    //getters and setters for Edit Account Button
    public JButton getEditAccountButton() {
        return editAccountButton;
    }
    public void setEditAccountButton(JButton editAccountButton) {
        this.editAccountButton = editAccountButton;
    }

    //getters and setters for Delete Account Button
    public JButton getDeleteAccountButton() {
        return deleteAccountButton;
    }
    public void setDeleteAccountButton(JButton deleteAccountButton) {
        this.deleteAccountButton = deleteAccountButton;
    }


}
